### PR TITLE
Support LTS + Current versions of Django

### PR DESCRIPTION
**Pull request by cwdavies**
This change updates our supported version range to the LTS release of Django (2.2) and the current release of Django (3.1).

## Additions

- Added support for Django 3.1

## Testing

- tox

### CODE REVIEW

**Comment by Scotchester** [comment]
@cwdavies #34 has been merged. Please rebase this PR on master.

**Comment by cwdavies** [comment]
> @cwdavies #34 has been merged. Please rebase this PR on master.

@Scotchester I rebased this PR and it ready for review.

**Comment by cwdavies** [comment]
> We should add the dj31 to the PR checker if we're adding it to the tox matrix right?

You should see dj31 added now.

**Comment by cwdavies** [comment]
Tests are passing using tox
```
...
py36-dj31-postgres installdeps: coverage==4.2, Django>=3.1,<3.2, psycopg2>=2.7
py36-dj31-postgres installed: asgiref==3.2.10,-e git+https://github.com/cfpb/django-college-costs-comparison@8aa9328cdeded44a924c48b23a78b5748138e34f#egg=comparisontool,coverage==4.2,dj-database-url==0.5.0,Django==3.1,django-haystack==3.0b1,django-localflavor==3.0.1,psycopg2==2.8.5,python-stdnum==1.14,pytz==2020.1,sqlparse==0.3.1
py36-dj31-postgres run-test-pre: PYTHONHASHSEED='2016631471'
py36-dj31-postgres run-test: commands[0] | coverage erase
py36-dj31-postgres run-test: commands[1] | coverage run ./manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
loading BAH file:/var/folders/m9/7kh3zqfs3sl36x0q8z049xrc0000gp/T/tmpa_rxlec7
.loading schools:/var/folders/m9/7kh3zqfs3sl36x0q8z049xrc0000gp/T/tmp5vw8p305
Schools loaded: 1, 2, ... done!
......................................
----------------------------------------------------------------------
Ran 39 tests in 0.343s

OK
Destroying test database for alias 'default'...
py36-dj31-postgres run-test: commands[2] | coverage report -m
Name                                                           Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------
comparisontool/__init__.py                                         1      0   100%
comparisontool/forms.py                                           10      0   100%
comparisontool/management/__init__.py                              0      0   100%
comparisontool/management/commands/__init__.py                     0      0   100%
comparisontool/management/commands/load_bah.py                    18      0   100%
comparisontool/management/commands/load_school.py                 35      0   100%
comparisontool/migrations/0001_initial.py                          5      0   100%
comparisontool/migrations/__init__.py                              0      0   100%
comparisontool/models.py                                          29      0   100%
comparisontool/search_indexes.py                                  15      0   100%
comparisontool/tests/__init__.py                                   0      0   100%
comparisontool/tests/forms.py                                      0      0   100%
comparisontool/tests/management/__init__.py                        0      0   100%
comparisontool/tests/management/commands/__init__.py               0      0   100%
comparisontool/tests/management/commands/test_load_bah.py         15      0   100%
comparisontool/tests/management/commands/test_load_school.py      15      0   100%
comparisontool/tests/settings.py                                  14      0   100%
comparisontool/tests/test_forms.py                                33      0   100%
comparisontool/tests/test_models.py                               15      0   100%
comparisontool/tests/test_search_indexes.py                       17      0   100%
comparisontool/tests/test_validators.py                           10      0   100%
comparisontool/tests/test_views.py                               103      0   100%
comparisontool/tests/views.py                                      0      0   100%
comparisontool/urls.py                                             4      0   100%
comparisontool/validators.py                                       7      0   100%
comparisontool/views.py                                           88      0   100%
--------------------------------------------------------------------------------------------
TOTAL                                                            434      0   100%
__________________________________________________ summary ___________________________________________________
  lint: commands succeeded
  py36-dj22-postgres: commands succeeded
  py36-dj31-postgres: commands succeeded
  congratulations :)
```

**Pull request merged**
